CREATE TABLE medias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fichier VARCHAR(255) NOT NULL,
    alt VARCHAR(255),
    contexte VARCHAR(100),
    date_creation DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE newsletter (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP
);
